apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dvn-workshop
    app.kubernetes.io/managed-by: kustomize
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
  ports:
    - name: http
      port: 80
      targetPort: http
