apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dvn-workshop
resources:
- namespace.yaml
- backend
- frontend
images:
- name: dvn-workshop/production/backend
  newName: 934384776856.dkr.ecr.us-east-1.amazonaws.com/dvn-backend
  newTag: a1193f9f9cbaa781b56c1bf5dcdd002150592bdf
- name: dvn-workshop/production/frontend
  newName: 934384776856.dkr.ecr.us-east-1.amazonaws.com/dvn-frontend
  newTag: a1193f9f9cbaa781b56c1bf5dcdd002150592bdf
